title: "[Question] "
labels: [question]
body:
- type: input
  id: question
  attributes:
    label: Question
    description: What is your question?
    placeholder: Question here...
  validations:
    required: true
- type: textarea
  id: details
  attributes:
    label: Additional Details
    description: Any other details for the question. This can be additional context, similar questions, or attempted answers.
    placeholder: Additional details
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Code of Conduct
    description: The Code of Conduct helps create a safe space for everyone. We require that everyone agrees to it.
    options:
    - label: I agree to follow this project's [Code of Conduct](https://github.com/comp-lang-comp/comp-lang-comp.github.io/blob/main/CODE_OF_CONDUCT.md)
      required: true