blank_issues_enabled: false
contact_links:
  - name: Questions, Ideas, Discussions
    url: https://github.com/comp-lang-comp/comp-lang-comp.github.io/discussions
    about: Ask and answer questions, and propose new features.
