blank_issues_enabled: false
contact_links:
  - name: Questions, Ideas, Discussions
    url: https://github.com/SurajSSingh/computer-languages-comparison/discussions
    about: Ask and answer questions, and propose new features.
