name: "Improve Tooling"
description: "Add or update tools around the project"
title: "[New Tool]: : <REPLACE WITH TITLE>"
labels: [enhancement, Tooling]
assignees: []
body: 
- type: input
  id: title
  attributes:
    label: "Title"
    description: "What is the title of your tooling contribution?"
    placeholder: "Title"
  validations:
    required: true
- type: textarea
  id: details
  attributes:
    label: "Explanations and Details"
    description: "What is your plan for this contribution?"
    placeholder: "What tool do you plan on making? Also include what language the tool will be written in."
  validations:
    required: true
- type: checkboxes
  id: checks
  attributes:
    label: Pre-issue checkboxes
    description: Please read and check these boxes before creating this issue
    options:
      - label: I have verified that there are no [**similar** *open* issues](https://github.com/comp-lang-comp/comp-lang-comp.github.io/issues) already being worked on and can contribute to.
        required: true
      - label: I have read the [appropriate contribution guide](../../CONTRIBUTING.md) before opening this issue.
        required: true
      - label: I have read [Code Of Conduct](../../CODE_OF_CONDUCT.md) and will abide by it for this contribution.
        required: true