name: Meta Change 
description: Change project issues, discussion, or similar
title: '[Improve Project]: : <REPLACE WITH TITLE>'
labels: enhancement, Meta
assignees: []
body: 
- type: input
  id: title
  attributes:
    label: "Title"
    description: "What is the title of your meta contribution?"
    placeholder: "Title"
  validations:
    required: true
- type: textarea
  id: details
  attributes:
    label: "Explanations and Details"
    description: "What is your plan for this contribution?"
    placeholder: "What are your plans for improving the project? Please make sure that this contribution would not be better served with any other issue template."
  validations:
    required: true
- type: dropdown
  id: area
  attributes:
    label: 
    description: 
    multiple: true
    options: 
      - "Issue Template"
      - "Discussion Template"
      - "Pull Request Template"
      - "Project Board"
      - "Labels"
      - "Wiki"
      - "CI/CD"
      - "Security"