name: Meta Change 
description: Change project issues, discussion, or similar
title: '[Improve Project]: <REPLACE WITH TITLE>'
labels: enhancement, Meta
assignees: []
body: 
- type: input
  id: title
  attributes:
    label: "Title"
    description: "What is the title of your meta contribution?"
    placeholder: "Title"
  validations:
    required: true
- type: textarea
  id: details
  attributes:
    label: "Explanations and Details"
    description: "Current plan for this contribution"
    placeholder: "What are your plans for improving the project? Please make sure that this contribution would not be better served with any other issue template."
  validations:
    required: true
- type: dropdown
  id: area
  attributes:
    label: "Area of Project"
    description: "What area(s) of the project are you planning on working on?"
    multiple: true
    options: 
      - "CONTRIBUTING file"
      - "README file"
      - "Slate Changes"
      - "Issue Template"
      - "Discussion Template"
      - "Pull Request Template"
      - "Project Board"
      - "Labels"
      - "Wiki"
      - "CI/CD"
      - "Security"
      - "Other - Leave Additional Comment"
- type: checkboxes
  id: checks
  attributes:
    label: Pre-issue checkboxes
    description: Please read and check these boxes before creating this issue
    options:
      - label: I have verified that there are no [**similar** *open* issues](https://github.com/comp-lang-comp/comp-lang-comp.github.io/issues) already being worked on and can contribute to.
        required: true
      - label: I have read the [appropriate contribution guide](../../CONTRIBUTING.md) before opening this issue.
        required: true
      - label: I have read [Code Of Conduct](../../CODE_OF_CONDUCT.md) and will abide by it for this contribution.
        required: true