name: Meta Change 
description: Change project issues, discussion, or similar
title: '[Improve Project]: <REPLACE WITH TITLE>'
labels: enhancement, Meta
assignees: []
body: 
- type: input
  id: title
  attributes:
    label: "Title"
    description: "What is the title of your meta contribution?"
    placeholder: "Title"
  validations:
    required: true
- type: textarea
  id: details
  attributes:
    label: "Explanations and Details"
    description: "Current plan for this contribution"
    placeholder: "What are your plans for improving the project? Please make sure that this contribution would not be better served with any other issue template."
  validations:
    required: true
- type: dropdown
  id: area
  attributes:
    label: "Area of Project"
    description: "What area(s) of the project are you planning on working on?"
    multiple: true
    options: 
      - "CONTRIBUTING file"
      - "README file"
      - "Slate Changes"
      - "Issue Template"
      - "Discussion Template"
      - "Pull Request Template"
      - "Project Board"
      - "Labels"
      - "Wiki"
      - "CI/CD"
      - "Security"
      - "Other - Leave Additional Comment"
